/**
 * scripts/calibrate.ts
 * End-to-end calibration pipeline runner.
 *
 *   ts-node scripts/calibrate.ts <loss-run.csv> [--apply]
 *
 * Without --apply: dry run — prints what would be promoted, no file writes.
 * With --apply: rewrites src/lib/vessel-classes.ts with the fitted output,
 *   preserving the file's docstring header. Always commits to git separately;
 *   the script never touches your VCS.
 *
 * Exit codes:
 *   0  : pipeline succeeded (dry run or apply)
 *   1  : input load failed (missing file, malformed CSV)
 *   2  : aggregation produced no usable classes
 *   3  : validation produced errors (exit before applying)
 *
 * Warnings do NOT exit nonzero — they're printed and the apply proceeds.
 * Errors always block apply. This matches industry calibration practice:
 * an actuary reviews warnings, doesn't trust the script to auto-decide.
 */

import fs   from "fs";
import path from "path";
import {
  loadLossRunFile,
  aggregateByVesselClass,
} from "../src/calibration/loader";
import {
  nullFitter,
  validateCalibratedConfig,
  partitionProblems,
  type CalibratedConfig,
  type Fitter,
} from "../src/calibration/fitter";

// ─── CLI parsing ──────────────────────────────────────────────────────────────

interface CliArgs {
  csvPath: string;
  apply:   boolean;
  fitter:  Fitter;
}

function parseCli(argv: string[]): CliArgs | null {
  const args = argv.slice(2);
  if (args.length === 0) return null;
  const csvPath = args[0];
  const apply   = args.includes("--apply");

  // Hook point: when a real fitter exists, accept --fitter=<name> and
  // dynamically route. For now, only nullFitter is available.
  const fitter = nullFitter;

  return { csvPath, apply, fitter };
}

function usage(): void {
  console.error(
    "Usage: ts-node scripts/calibrate.ts <loss-run.csv> [--apply]\n" +
    "\n" +
    "  Without --apply: dry run, no file writes.\n" +
    "  With --apply:    rewrite src/lib/vessel-classes.ts on success.\n"
  );
}

// ─── Pretty-print ─────────────────────────────────────────────────────────────

function printAggregateStats(stats: ReturnType<typeof aggregateByVesselClass>): void {
  console.log(`Aggregated ${stats.stats.size} vessel class(es):`);
  for (const [key, s] of stats.stats.entries()) {
    console.log(
      `  ${key}:\n` +
      `    vessel_years:      ${s.total_vessel_years}\n` +
      `    total_claims:      ${s.total_claims}\n` +
      `    claim_frequency:   ${s.claim_frequency_rate.toFixed(4)} /year\n` +
      `    mean_severity:     ${s.mean_severity_per_claim?.toFixed(2) ?? "n/a"} USD\n` +
      `    loss_ratio:        ${(s.loss_ratio * 100).toFixed(1)}%\n` +
      `    years:             ${s.earliest_year}–${s.latest_year}`
    );
  }
  if (stats.dropped.length > 0) {
    console.log(`Dropped ${stats.dropped.length} unmapped labels:`);
    for (const d of stats.dropped) {
      console.log(`  "${d.vessel_class}" (${d.rows} rows)`);
    }
  }
}

function printProblems(calibrated: CalibratedConfig, problems: ReturnType<typeof partitionProblems>): void {
  const { errors, warnings } = problems;
  if (errors.length === 0 && warnings.length === 0) {
    console.log(`  ${calibrated.vessel_class_key}: validation clean.`);
    return;
  }
  console.log(`  ${calibrated.vessel_class_key}: ${errors.length} error(s), ${warnings.length} warning(s).`);
  for (const e of errors) {
    console.log(`    ERROR ${e.field} = ${JSON.stringify(e.value)}: ${e.reason}`);
  }
  for (const w of warnings) {
    console.log(`    WARN  ${w.field} = ${JSON.stringify(w.value)}: ${w.reason}`);
  }
}

// ─── File rewrite ─────────────────────────────────────────────────────────────

const VESSEL_CLASSES_PATH = path.resolve(__dirname, "..", "src", "lib", "vessel-classes.ts");

/**
 * Rewrites vessel-classes.ts with the calibrated output. Preserves the
 * top-of-file docstring; replaces only the constant exports.
 *
 * Strategy: regenerate the file from scratch with the fitted values.
 * Hand-maintained edits to the constants get overwritten — that's the
 * point. If you want hand-tuning, do it AFTER the script runs and
 * commit your edits.
 */
function rewriteVesselClasses(calibrations: CalibratedConfig[]): void {
  // Build the file contents
  const banner = `/**
 * src/lib/vessel-classes.ts
 *
 * AUTOMATICALLY GENERATED by scripts/calibrate.ts.
 * Do not hand-edit. Re-run calibration with new loss runs to update.
 *
 * Provenance for each class:
${calibrations.map(c =>
  ` *   ${c.vessel_class_key}:\n` +
  ` *     fitter:        ${c.provenance.fitter_name} v${c.provenance.fitter_version}\n` +
  ` *     input years:   ${c.provenance.input_year_range[0]}–${c.provenance.input_year_range[1]}\n` +
  ` *     vessel_years:  ${c.provenance.input_vessel_years}\n` +
  ` *     timestamp:     ${c.provenance.fit_timestamp}\n` +
  ` *     notes:         ${c.provenance.notes ?? "(none)"}`
).join("\n *\n")}
 */

import type { VesselClassConfig } from "./premium-pricing";
`;

  const exports = calibrations.map(c => {
    const exportName = c.vessel_class_key === "CONTAINER_SHIP"
      ? "CONTAINER_SHIP_CONFIG"
      : "TUGBOAT_CONFIG";
    return `\n// ─── ${c.vessel_class_key} ──────────────────────────────────────────────\n\n` +
           `export const ${exportName}: VesselClassConfig = ${stringifyConfig(c.config)};\n`;
  }).join("");

  const full = banner + exports;

  fs.writeFileSync(VESSEL_CLASSES_PATH, full, "utf-8");
}

function stringifyConfig(config: unknown): string {
  // Custom stringify: pretty-printed, 2-space indent, double-quoted keys.
  return JSON.stringify(config, null, 2)
    // Convert "key": → key: (still valid TS for object literals where the key is identifier-safe)
    .replace(/"(\w+)":/g, "$1:");
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = parseCli(process.argv);
  if (!args) {
    usage();
    process.exit(1);
  }

  // 1. Load
  console.log(`Loading loss run: ${args.csvPath}`);
  let parsed: ReturnType<typeof loadLossRunFile>;
  try {
    parsed = loadLossRunFile(args.csvPath);
  } catch (err) {
    console.error(`Load failed: ${(err as Error).message}`);
    process.exit(1);
  }

  console.log(`  parsed ${parsed.records.length} records, skipped ${parsed.skipped.length}`);
  if (parsed.skipped.length > 0) {
    for (const s of parsed.skipped.slice(0, 5)) {
      console.log(`    line ${s.line_number}: ${s.reason}`);
    }
    if (parsed.skipped.length > 5) {
      console.log(`    ... and ${parsed.skipped.length - 5} more`);
    }
  }

  // 2. Aggregate
  const aggregated = aggregateByVesselClass(parsed.records);
  console.log();
  printAggregateStats(aggregated);

  if (aggregated.stats.size === 0) {
    console.error("\nNo vessel classes mapped — nothing to calibrate.");
    process.exit(2);
  }

  // 3. Fit
  console.log(`\nFitting with ${args.fitter === nullFitter ? "nullFitter (no real fitting)" : "<custom fitter>"}:`);
  const calibrations: CalibratedConfig[] = [];
  for (const stats of aggregated.stats.values()) {
    calibrations.push(args.fitter(stats));
  }

  // 4. Validate
  console.log("\nValidation:");
  let hasErrors = false;
  for (const c of calibrations) {
    const problems = partitionProblems(validateCalibratedConfig(c));
    printProblems(c, problems);
    if (problems.errors.length > 0) hasErrors = true;
  }
  if (hasErrors) {
    console.error("\nValidation errors present — aborting before any promotion.");
    process.exit(3);
  }

  // 5. Promote or dry-run
  if (args.apply) {
    console.log(`\nWriting ${VESSEL_CLASSES_PATH}...`);
    rewriteVesselClasses(calibrations);
    console.log("Done. Review the diff with `git diff src/lib/vessel-classes.ts` and commit.");
  } else {
    console.log(
      "\nDry run complete. To apply: re-run with --apply.\n" +
      "Preview of what would be written:"
    );
    for (const c of calibrations) {
      console.log(`\n--- ${c.vessel_class_key} ---`);
      console.log(JSON.stringify(c.config, null, 2));
    }
  }
}

main().catch(err => {
  console.error("Fatal:", err);
  process.exit(1);
});
